from pathlib import Path
import re

root = Path(".")
main_path = root / "app/src/main/java/com/example/dinocompanion/MainActivity.kt"
s = main_path.read_text(encoding="utf-8")

# v1.46 is the XML UI generated by patch_v1_41.py. Fix the real source of the
# screen-stacking bug: each page must replace the previous page in content.
s = s.replace(
    'private fun page(title:String):LinearLayout{\n        DinoLife.tick(prefs)',
    'private fun page(title:String):LinearLayout{\n        content.removeAllViews()\n        DinoLife.tick(prefs)'
)

# Make the evolution button actually open an evolution screen.
s = s.replace(
    'put(r2,button("🧬  EVOLVE",Color.rgb(91,128,56)){toast("Evolution requirements shown above")},-2,1f)',
    'put(r2,button("🧬  EVOLVE",Color.rgb(91,128,56)){evolvePage()},-2,1f)'
)

# Upgrade Play by replacing the method between exact Kotlin method boundaries.
play_method = r'''    private fun play(){
        val p=page("PLAY GAMES")
        put(p,text("Choose a game and earn XP, coins and happiness.",15f,true,Color.rgb(255,222,139)))
        val games=listOf(
            Triple("BUBBLE POP","Tap fast to pop bubbles",15),
            Triple("CATCH THE FOOD","Catch food for your Dino",20),
            Triple("FRUIT TOSS","Build your bond with fruit",25)
        )
        games.forEachIndexed { i, game ->
            val c=card()
            put(c,text(game.first,18f,true,if(i==0)Color.rgb(102,199,255)else if(i==1)Color.rgb(255,192,72)else Color.rgb(134,239,74)))
            put(c,text(game.second,12f,false,Color.rgb(220,235,221)))
            put(c,dinoView(125))
            put(c,button("PLAY  •  +"+game.third+" XP",Color.rgb(73,164,60)){
                happiness=(happiness+8+i*2).coerceAtMost(100)
                energy=(energy-4).coerceAtLeast(0)
                coins+=2+i
                bond=(bond+2+i).coerceAtMost(100)
                addXp(game.third)
                toast(game.first+" complete! +"+game.third+" XP")
                play()
            })
            put(p,c)
        }
        put(p,text("Play regularly to build your Dino's bond.",13f,true,Color.rgb(255,222,139)))
        content.addView(p)
    }
'''
play_start=s.index("    private fun play(){")
play_end=s.index("    private fun shop(){",play_start)
s=s[:play_start]+play_method+s[play_end:]
# Add a proper evolution page.
marker='''    private fun choose(){'''
evolve='''    private fun evolvePage(){\n        val p=page("EVOLUTION")\n        put(p,text("Help "+dinoName+" grow through four stages.",15f,true,Color.rgb(255,222,139)))\n        val c=card()\n        put(c,dinoView(260))\n        put(c,text("STAGE "+stage+" / 4",20f,true,Color.rgb(157,235,94)))\n        val need=stage*100\n        if(stage<4){\n            put(c,text(xp+" / "+need+" XP to evolve",13f,true,Color.WHITE))\n            put(c,ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal).apply{\n                max=need;progress=xp.coerceIn(0,need)\n                progressTintList=android.content.res.ColorStateList.valueOf(Color.rgb(102,231,58))\n                progressBackgroundTintList=android.content.res.ColorStateList.valueOf(Color.rgb(24,31,32))\n            },dp(12))\n            put(c,button(if(xp>=need)"EVOLVE NOW" else "KEEP PLAYING",Color.rgb(91,128,56)){\n                if(xp>=need){ addXp(0); evolvePage() } else toast("Earn "+(need-xp)+" more XP")\n            })\n        }else{\n            put(c,text("MAX EVOLUTION REACHED",15f,true,Color.rgb(255,222,139)))\n        }\n        put(p,c)\n        put(p,button("‹  BACK HOME",Color.rgb(65,128,172)){home()})\n        content.addView(p)\n    }\n\n'''
if marker in s and 'private fun evolvePage()' not in s: s=s.replace(marker,evolve+marker)

# Settings version and a clean, single daily reward per calendar day.
s=s.replace('Dino Companion 1.45','Dino Companion 1.46')
s=s.replace(
    'put(daily,button("FREE DAILY COIN",Color.rgb(185,125,47)){coins++;save();shop()})',
    'put(daily,button("FREE DAILY REWARD",Color.rgb(185,125,47)){val day=java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_YEAR);val claimed=prefs.getInt("daily_reward_day",-1);if(claimed!=day){coins+=10;gems+=1;prefs.edit().putInt("daily_reward_day",day).apply();save();toast("Daily reward claimed! +10 coins +1 gem");shop()}else toast("Daily reward already claimed today")})'
)

# Persist and show the current v1.46 build label.
main_path.write_text(s,encoding="utf-8")
g = root / "app/build.gradle.kts"
gs = g.read_text(encoding="utf-8")
import re
gs=re.sub(r'applicationId\s*=\s*"[^"]+"','applicationId = "com.example.dinocompanion.v146"',gs)
gs=re.sub(r'versionCode\s*=\s*\d+','versionCode = 49',gs)
gs=re.sub(r'versionName\s*=\s*"[^"]+"','versionName = "1.46"',gs)
g.write_text(gs,encoding="utf-8")
(root/"BUILD_VERSION.txt").write_text("Dino Companion v1.46 UI and interaction rebuild\\n",encoding="utf-8")
print("Dino Companion v1.46 UI rebuild generated")
